// === LEVELS DEFINITIONS ===
// TODOs 7, 11, and 12 will require changes to this section
const LEVELS = [
  {
    name: "Level 1",
    speed: 3,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 700, y: groundY },
      {
        type: "enemy",
        kind: "bug",
        x: 930,
        y: groundY - 160,
        contactHealthChange: -10,
      },
      { type: "powerup", kind: "healthUp", x: 1575, y: groundY - 180 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 900,
        y: groundY - 100,
      },
      { type: "platform", kind: "basicPlatform", x: 600, y: groundY - 60 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1200,
        y: groundY - 40,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1500,
        y: groundY - 120,
        hp: 0,
      },

      { type: "goal", kind: "flag", x: 2000, y: groundY },
    ],
  },
  {
    name: "Level 2",
    speed: 6,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 700, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1100, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1500, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1900, y: groundY },
      { type: "obstacle", kind: "spikes", x: 2300, y: groundY },
      { type: "enemy", kind: "bug", x: 850, y: groundY - 140 },
      { type: "enemy", kind: "bug", x: 1250, y: groundY },
      { type: "enemy", kind: "bug", x: 1650, y: groundY - 140 },
      { type: "enemy", kind: "bug", x: 2050, y: groundY },
      { type: "enemy", kind: "bug", x: 2450, y: groundY - 140 },
      { type: "powerup", kind: "healthUp", x: 650, y: groundY - 140 },
      { type: "powerup", kind: "healthUp", x: 1350, y: groundY - 180 },
      { type: "powerup", kind: "healthUp", x: 2150, y: groundY - 160 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 600,
        y: groundY - 80,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1000,
        y: groundY - 120,
        contactHealthChange: -5,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1400,
        y: groundY - 100,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1800,
        y: groundY - 140,
        contactHealthChange: -10,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 2200,
        y: groundY - 80,
        hp: 0,
      },
      { type: "goal", kind: "flag", x: 2800, y: groundY },
    ],
  },
  {
    name: "Level 3",
    speed: 9,
    gameObjects: [
      { type: "obstacle", kind: "spikes", x: 700, y: groundY },
      { type: "obstacle", kind: "spikes", x: 850, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1000, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1150, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1300, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1450, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1600, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1750, y: groundY },
      { type: "obstacle", kind: "spikes", x: 1900, y: groundY },
      { type: "obstacle", kind: "spikes", x: 2050, y: groundY },
      { type: "enemy", kind: "bug", x: 750, y: groundY - 160 },
      { type: "enemy", kind: "bug", x: 900, y: groundY - 140 },
      { type: "enemy", kind: "bug", x: 1050, y: groundY - 160 },
      { type: "enemy", kind: "bug", x: 1200, y: groundY - 140 },
      { type: "enemy", kind: "bug", x: 1350, y: groundY - 160 },
      { type: "enemy", kind: "bug", x: 1500, y: groundY - 140 },
      { type: "enemy", kind: "bug", x: 1650, y: groundY - 160 },
      { type: "enemy", kind: "bug", x: 1800, y: groundY - 140 },
      { type: "enemy", kind: "bug", x: 1950, y: groundY - 160 },
      { type: "enemy", kind: "bug", x: 2100, y: groundY - 140 },
      { type: "powerup", kind: "healthUp", x: 650, y: groundY - 140 },
      { type: "powerup", kind: "healthUp", x: 950, y: groundY - 180 },
      { type: "powerup", kind: "healthUp", x: 1250, y: groundY - 160 },
      { type: "powerup", kind: "healthUp", x: 1550, y: groundY - 200 },
      { type: "powerup", kind: "healthUp", x: 1850, y: groundY - 180 },
      { type: "powerup", kind: "healthUp", x: 2150, y: groundY - 160 },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 600,
        y: groundY - 60,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 900,
        y: groundY - 100,
        contactHealthChange: -5,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1200,
        y: groundY - 80,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1500,
        y: groundY - 120,
        contactHealthChange: -10,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 1800,
        y: groundY - 100,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 2100,
        y: groundY - 80,
        contactHealthChange: -5,
      },
      {
        type: "platform",
        kind: "basicPlatform",
        x: 2400,
        y: groundY - 120,
        hp: 0,
      },
      { type: "goal", kind: "flag", x: 2900, y: groundY },
    ],
  },
];

let currentLevel = LEVELS[0];
let currentLevelIndex = 0;
// === END LEVELS DEFINITIONS ===

// === DEFAULT VALUES FOR EACH "type" AND "kind" OF OBJECT (STUDENT-EDITABLE) ===
const DEFAULT_VALUES = {
  obstacle: {
    spikes: {
      imageUrl: "images/interactable/spikes.png",
      width: 48,
      height: 48,
      hitWidth: 40,
      hitHeight: 44,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: -20,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: false,
    },
  },
  enemy: {
    bug: {
      imageUrl: "images/interactable/bug.png",
      width: 75,
      height: 75,
      hitWidth: 75,
      hitHeight: 75,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 75,
      contactHealthChange: -30,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 50,
      hp: 3,
      collect: false,
    },
  },
  powerup: {
    healthUp: {
      imageUrl: "images/interactable/health-up.png",
      width: 32,
      height: 32,
      hitWidth: 32,
      hitHeight: 32,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 32,
      contactHealthChange: +15,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  goal: {
    flag: {
      imageUrl: "images/interactable/flag.png",
      width: 100,
      height: 100,
      hitWidth: 100,
      hitHeight: 100,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: 0,
      contactHealthChange: 0,
      contactScoreChange: +100,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: 0,
      collect: true,
    },
  },
  platform: {
    basicPlatform: {
      imageUrl: "images/interactable/basic-platform.png",
      width: 200,
      height: 50,
      hitWidth: 200,
      hitHeight: 50,
      speedX: 0,
      speedY: 0,
      minY: 0,
      maxY: groundY - 50,
      contactHealthChange: 0,
      contactScoreChange: 0,
      projectileHealthChange: 0,
      projectileScoreChange: 0,
      hp: Infinity,
      collect: false,
    },
  },
};
// === END DEFAULT VALUES ===
